# Generated by Django 4.2 on 2024-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
